bind 127.0.0.1
protected-mode yes
port 0
unixsocket /run/faucet-machine-funding/redis.sock
unixsocketperm 700
daemonize no
supervised no
dir /var/lib/faucet-machine-funding
appendonly yes
appendfsync always
appendfilename "appendonly.aof"
save ""
loglevel notice
